import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container } from "../components/container";
import { PostsContainer } from "../components/posts-container";
import { Post } from "./api/posts";

const HomePage: NextPage<{ posts: Post[] }> = (props) => {
  return (
    <Container>
      <Head>
        <title>Classic | Better then Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostsContainer>
        {props.posts.map((post) => {
          return (
            <div key={post.id} style={{ display: "flex" }}>
              <Image
                src={post.imageUrl}
                alt="Post image"
                width="640"
                height="480"
              />
            </div>
          );
        })}
      </PostsContainer>
    </Container>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/posts`);
  const { posts } = await res.json();

  // Pass data to the page via props
  return { props: { posts } };
}

export default HomePage;
